<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hello_disabledcursor-not-allowed</name>
   <tag></tag>
   <elementGuidId>fcedfb28-a6d7-4fc1-87f2-298c083bbe5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2419694f-7d06-48a5-b05e-8c6600b1b09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>dedce23d-f53b-42fd-9262-a81d7dc07431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled:cursor-not-allowed</value>
      <webElementGuid>de1e88a2-bc0c-4a87-b84d-6052f48d5c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13314e0d-4402-4d7b-9c6a-ee4dc797501b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-placeholder-shown</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>490ec6ce-2da2-4ea1-a005-cbfc745722b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>faebe611-0792-4bb5-839b-f787309ed6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\d+$</value>
      <webElementGuid>a7840969-ce8b-4efb-9499-ab7cdaeac3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>25098dae-3bc1-4c9a-b032-24af8bee8491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-mss</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>76905996-f403-40a1-8c1e-d62aab58b5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-mse</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93e5e5d5-a136-4c4e-8093-4b52572eece2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r7:&quot;)/div[@class=&quot;px-5 sm:px-0&quot;]/form[@class=&quot;mt-4 space-y-4&quot;]/div[@class=&quot;flex items-center justify-between p-1 my-8 overflow-hidden&quot;]/div[@class=&quot;flex items-center w-full justify-between gap-2 has-[:disabled]:opacity-50&quot;]/div[7]/input[@class=&quot;disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>358e724c-d01d-4ef1-bfab-419d54380add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>f646de7d-1c67-4abc-98df-8a8122697896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r7:']/div/form/div/div/div[7]/input</value>
      <webElementGuid>cf5f577b-9311-476c-9c91-5f1e444a17fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/input</value>
      <webElementGuid>04fcb7a4-1c44-4769-8dbd-fec1920a6d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
