<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Keluar</name>
   <tag></tag>
   <elementGuidId>4d99bb4c-680e-4f88-ad9c-ccb12b134948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.flex.items-center.rounded-md.text-sm.font-medium.text-red-400</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1ve:']/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Keluar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>247497e4-4cb5-487c-b66d-800eb67aedbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center rounded-md text-sm font-medium text-red-400</value>
      <webElementGuid>c43be076-aa9c-4e78-ad4c-c8705fbd6b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>cc2eb4b5-18d2-4977-ba24-0f1d799936b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1ve:&quot;)/div[@class=&quot;relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50&quot;]/div[@class=&quot;mt-1 cursor-pointer content-end p-3 md:border-t&quot;]/p[@class=&quot;flex items-center rounded-md text-sm font-medium text-red-400&quot;]</value>
      <webElementGuid>88ddc223-17b5-4f70-abb4-5456399690f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1ve:']/div/div/p</value>
      <webElementGuid>b52744e2-093d-4a65-aedb-b0e2b83c1ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::p[1]</value>
      <webElementGuid>0fac04cd-27aa-4826-bc98-bc5fd81e6e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[1]/following::p[1]</value>
      <webElementGuid>a1eefae6-ae37-4e4e-bd53-1169a1ab3191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>186784cd-517f-4bb3-b98f-9ef3d05e7d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/p</value>
      <webElementGuid>12a621b4-480a-4465-8995-dfff21c7ca64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>0e0359fc-86ed-4246-9f66-5578ecc54177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
